---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-values
  namespace: observability
data:
  values.yaml: |
    # Loki Configuration
    loki:
      auth_enabled: false
      deploymentMode: SingleBinary
      useTestSchema: true
      common:
        replication_factor: 1
        path_prefix: /loki
      storage:
        type: filesystem

    singleBinary:
      replicas: 0

    simpleScalable:
      enabled: false

    gateway:
      enabled: true
      replicas: 1
      service:
        type: NodePort
