apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-generator
  namespace: observability
  labels:
    app: traffic-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic-generator
  template:
    metadata:
      labels:
        app: traffic-generator
    spec:
      containers:
        - name: traffic-generator
          image: traffic-generator:v1
          imagePullPolicy: Never
          env:
            - name: OTEL_SERVICE_NAME
              value: "user"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://alloy.observability.svc:4318"
            - name: JS_APP_URL
              value: "http://sample-javascript-traces-app:8082"
            - name: PYTHON_APP_URL
              value: "http://sample-traces-app:8081"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: traffic-generator
  namespace: observability
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: traffic-generator
