apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - repositories.yaml
  - flux-system/gotk-components.yaml
  - flux-system/gotk-sync.yaml
  - flux-system/source-rbac.yaml
  - apps-kustomization.yaml
  - infrastructure-kustomization.yaml
